library("rmarkdown")
setwd("workshop")
render("notebook-00.Rmd", output_format = "md_document")
render("notebook-01.Rmd", output_format = "md_document")
render("notebook-02.Rmd", output_format = "md_document")
